# Define openai model
# default: text-davinci-003
model: "text-davinci-003"

# api key
# generate by creating account on openai platform
# https://openai.com/api/
api_key: ""

# gui name
gui_name: "Choose language"

# Define max words count in single name
# default: 2
max_words_count: 2

message:
  loading: "&aLoading..."
  success: "&aGenerated name:"
  error: "&cError:"