# Define openai model
# default: text-davinci-003
model: "text-davinci-003"

# api key
# generate by creating account on openai platform
# https://openai.com/api/
api_key: ""

# gui name
gui_name: "&aChoose language"

# Define max words count in single name
# default: 2
max_words_count: 2

message:
  loading: "Loading..."
  success: "Generated name:"
  error: "Error:"